apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradecondition
  labels:
    app: tradecondition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradecondition
  template:
    metadata:
      labels:
        app: tradecondition
    spec:
      containers:
        - name: tradecondition
          image: username/tradecondition:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5